databases:
  - name: dpg-cqdakit6l47c73frqehg-a 
    plan: free
    databaseName: unique_gqab
    user: unique_gqab_user

services:
  - type: web
    plan: free
    name: rendertr
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: configdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4